name: "Bug Report"
description: "Report a bug to help us improve DullJS"
title: "Bug Report: "
labels: bug
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: |
        Please provide a clear and concise description of the bug you encountered.
      placeholder: |
        Example: When I use DullJS in my project, I encounter the following issue...

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Outline the steps to reproduce the bug, if applicable.
      placeholder: |
        If possible, provide steps to reproduce the issue.

  - type: textarea
    attributes:
      label: Expected Behavior
      description: "What did you expect to happen?"
      placeholder: |
        Describe the expected behavior.

  - type: textarea
    attributes:
      label: Environment Details
      description: |
        Please provide information about your environment, such as the DullJS version and Node.js version.
      placeholder: |
        Example:
        - DullJS Version: X.X.X
        - Node.js Version: XX.XX.XX

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any additional context that might help us understand the bug better.
      placeholder: |
        Additional information...
