name: "Feature Request"
description: "Suggest a new feature or enhancement for DullJS"
title: "Feature Request: "
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: |
        Please provide a clear and concise description of the feature or enhancement you'd like to request.
      placeholder: |
        Example: I would like to suggest adding a new method that performs...

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any additional context, examples, or details that might help us understand your request better.
      placeholder: |
        Additional information...